version: '3.5'

services:
  maildev:
    image: djfarrelly/maildev
    networks:
      web:
      mail:
        aliases:
          - mail.external.home
    restart: unless-stopped
    labels:
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.backend: "maildev"
      traefik.basic.frontend.rule: "Host:mail.local.home.lan,mail.local"
      traefik.basic.port: 80
      traefik.basic.protocol: http

  traefik:
    image: traefik:1.7-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  ldap:
    image: scottsmith/ldap-ad-it
    restart: unless-stopped
    ports:
      - 389:10389
    networks:
      database:
        aliases:
          - ldap

  redis:
    image: redis:5.0.8
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      database:
        aliases:
          - global-app-redis

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql-files
    ports:
      - 3306:3306
    networks:
      - database
    restart: unless-stopped

networks:
  web:
    external: true
    name: web
  mail:
    external: true
    name: mail
  database:
    external: true
    name: database

volumes:
  mysql-data:
    external: true
    name: mysql-data
