version: '3.5'

services:
  maildev:
    image: djfarrelly/maildev
    networks:
      web:
        aliases:
        - mail.local
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.maildev.rule: "Host(`mail.local`)"
      traefik.http.routers.maildev.entrypoints: web
      traefik.http.services.maildev.loadbalancer.server.port: 80

  traefik:
    image: traefik:v2.2
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
    - "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedByDefault=false"
    - "--providers.docker.network=web"
    - "--providers.docker.swarmMode=false"
    - "--providers.docker.swarmModeRefreshSeconds=10"
    - "--providers.docker.watch"
    - "--entrypoints.web.address=:80"
    - "--entryPoints.web.forwardedHeaders.insecure"
    restart: unless-stopped
    networks:
    - web
    ports:
    - "80:80"
    - "8080:8080"

  redis:
    image: redis:5.0.8
    restart: unless-stopped
    ports:
    - 6379:6379
    networks:
    - web

  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
    - 27017:27017
    restart: unless-stopped
    networks:
    - web

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - mysql-data:/var/lib/mysql-files
    ports:
    - 13306:3306
    networks:
      web:
        aliases:
        - mysql
    restart: unless-stopped

networks:
  web:
    external: true

volumes:
  mysql-data:
    external: true
