version: '3.5'

services:
  maildev:
    image: djfarrelly/maildev
    networks:
      - web
      - smtp
    restart: unless-stopped
    labels:
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.backend: "maildev"
      traefik.basic.frontend.rule: "Host:mail.local.home.lan"
      traefik.basic.port: 80
      traefik.basic.protocol: http

  traefik:
    image: traefik:1.5.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  ldap:
    image: scottsmith/ldap-ad-it
    restart: unless-stopped
    ports:
      - 389:10389
    networks:
      ldap:
        aliases:
          - ldap

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql-files
    ports:
      - 3306:3306
    networks:
      - mysql
    restart: unless-stopped

networks:
  web:
    external: true
    name: web
  smtp:
    external: true
    name: smtp
  ldap:
    external: true
    name: ldap
  mysql:
    external: true
    name: mysql

volumes:
  mysql-data:
    external: true
    name: mysql-data
