version: '3.5'

services:
  maildev:
    image: djfarrelly/maildev
    networks:
      - web
      - smtp
    restart: unless-stopped
    labels:
      traefik.docker.network: web
      traefik.enable: "true"
      traefik.backend: "maildev"
      traefik.basic.frontend.rule: "Host:mail.local.home.lan"
      traefik.basic.port: 8080
      traefik.basic.protocol: http

  traefik:
    image: traefik:1.5.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

networks:
  web:
    external: true
    name: web
  smtp:
    external: true
    name: smtp
